---
title: Package utility - src
---
%% Sorgente: project/src/src/utility/Keyboard.java
classDiagram
  direction TB
  namespace utility {
    class Keyboard
  }

  class Keyboard {
    -printErrors: boolean$
    -errorCount: int$
    -current_token: String$
    -reader: StringTokenizer$
    -in: BufferedReader$
    +getErrorCount() int$
    +resetErrorCount(in count: int)$
    +getPrintErrors() boolean$
    +setPrintErrors(in flag: boolean)$
    -error(in str: String)$
    -getNextToken() String$
    -getNextToken(in skip: boolean) String$
    -getNextInputToken(in skip: boolean) String$
    +endOfLine() boolean$
    +readString() String$
    +readWord() String$
    +readBoolean() boolean$
    +readChar() char$
    +readInt() int$
    +readLong() long$
    +readFloat() float$
    +readDouble() double$
  }
